services:
  patterns:
    build: ./compose
    container_name: thirsty-ai
    restart: always
    ports:
      - "8080:80"

    volumes:
      - "./src:/var/www/html"
      - "./compose/nginx.conf:/etc/nginx/nginx.conf"
      - "./compose/php.ini:/usr/local/etc/php/conf.d/php.ini"
